### ISSUE TITLE
Update to account for recent iOS WebKit changes related to 300ms click delay

### ISSUE THREAD

**Issue by cvrebert** [patrickhlauke/getting-touchy-presentation#3] opened 2015-11-27 02:05 UTC
- http://trac.webkit.org/changeset/191644
- http://trac.webkit.org/changeset/191452

**Comment by patrickhlauke** [comment] 2015-11-27 09:18
Admittedly, I keep notes about what needs updating on the presentation separate from here...otherwise I'd be able to tell you "Duplicate of XXX. Search more next time" ;)

In seriousness though, glad you're looking over these slides. Planning a major restructure for next year, so watch this space.

**Comment by cvrebert** [comment] 2015-12-07 02:46
~~Also, https://patrickhlauke.github.io/getting-touchy-presentation/?full#163 mentions iOS's non-standard gesture events. Perhaps [Microsoft's gesture events](https://msdn.microsoft.com/en-us/library/dn433243%28v=vs.85%29.aspx) would also be worth mentioning?~~

**Comment by patrickhlauke** [comment] 2015-12-07 09:25
i briefly touch on MS gesture events here http://patrickhlauke.github.io/getting-touchy-presentation/?full#282 (though pointing to a different page). may revise where it's pointing to :)

**Comment by cvrebert** [comment] 2015-12-07 09:30
Ah. Must've missed it due to the distance and lack of keywords I'd been searching for. Sorry for the noise.

**Comment by patrickhlauke** [comment] 2015-12-07 09:41
no worries, it's actually something i should look into more deeply, if only to get more familiar with it

**Comment by patrickhlauke** [comment] 2016-03-09 01:39
Closing via https://github.com/patrickhlauke/getting-touchy-presentation/commit/e830199a786e68f9633c2dd72925d66a5a1f0355

**Closed as completed by patrickhlauke** 2016-03-09 01:39 UTC
